export const ROUTES = {
  LOGIN: '/login',
  PROJECTS: '/projects',
  PROJECT_DETAIL: '/projects/:id',
  AGENTS: '/agents',
  AGENT_EDIT: '/agents/:id',
  MODELS: '/models',
  WORKFLOWS: '/workflows',
  WORKFLOW_EDITOR: '/workflows/:id/editor',
  RUNS: '/runs',
  RUN_DETAIL: '/runs/:id',
  UI_REFERENCE_HOME: '/ui-reference',
  UI_REFERENCE: '/ui-reference/workflow-studio',
  UI_REFERENCE_LOGIN: '/ui-reference/login',
  UI_REFERENCE_PROJECT_LIST: '/ui-reference/projects',
  UI_REFERENCE_PROJECT_DETAIL: '/ui-reference/projects/detail',
  UI_REFERENCE_AGENT_LIST: '/ui-reference/agents',
  UI_REFERENCE_AGENT_EDIT: '/ui-reference/agents/edit',
  UI_REFERENCE_MODEL_CONFIG: '/ui-reference/models',
  UI_REFERENCE_WORKFLOW_LIST: '/ui-reference/workflows',
  UI_REFERENCE_WORKFLOW_EDITOR: '/ui-reference/workflow-studio',
  UI_REFERENCE_RUN_LIST: '/ui-reference/runs',
  UI_REFERENCE_RUN_DETAIL: '/ui-reference/runs/detail',
} as const
