import json

BUILTIN_ROLE_TEMPLATES = [
    {
        "key": "generic_assistant",
        "name": "Generic Assistant",
        "category": "general",
        "description": "General-purpose assistant for common tasks",
        "execution_mode": "normal_llm",
        "default_role_name": "assistant",
        "default_skill_ids": [],
        "default_tool_ids": [],
        "policy_config": {
            "max_iterations": 1,
            "allow_file_write": False,
            "run_lint": False,
            "run_build": False,
            "run_unit_tests": False,
        },
    },
    {
        "key": "product_manager",
        "name": "Product Manager",
        "category": "product",
        "description": "Analyzes requirements and produces structured PRDs",
        "execution_mode": "normal_llm",
        "default_role_name": "product_manager",
        "default_skill_ids": [],
        "default_tool_ids": [],
        "policy_config": {
            "max_iterations": 1,
            "allow_file_write": False,
            "run_lint": False,
            "run_build": False,
            "run_unit_tests": False,
        },
    },
    {
        "key": "backend_engineer",
        "name": "Backend Engineer",
        "category": "engineering",
        "description": "Writes backend service code, executes builds and tests",
        "execution_mode": "code_runtime",
        "default_role_name": "backend_engineer",
        "default_skill_ids": [],
        "default_tool_ids": [],
        "policy_config": {
            "max_iterations": 3,
            "allow_file_write": False,
            "run_lint": True,
            "run_build": False,
            "run_unit_tests": True,
        },
    },
    {
        "key": "frontend_engineer",
        "name": "Frontend Engineer",
        "category": "engineering",
        "description": "Implements UI components and frontend logic",
        "execution_mode": "code_runtime",
        "default_role_name": "frontend_engineer",
        "default_skill_ids": [],
        "default_tool_ids": [],
        "policy_config": {
            "max_iterations": 3,
            "allow_file_write": False,
            "run_lint": True,
            "run_build": False,
            "run_unit_tests": True,
        },
    },
    {
        "key": "fullstack_engineer",
        "name": "Fullstack Engineer",
        "category": "engineering",
        "description": "Handles both frontend and backend development tasks",
        "execution_mode": "code_runtime",
        "default_role_name": "fullstack_engineer",
        "default_skill_ids": [],
        "default_tool_ids": [],
        "policy_config": {
            "max_iterations": 3,
            "allow_file_write": False,
            "run_lint": True,
            "run_build": True,
            "run_unit_tests": True,
        },
    },
    {
        "key": "research_analyst",
        "name": "Research Analyst",
        "category": "research",
        "description": "Conducts research and produces analysis reports",
        "execution_mode": "normal_llm",
        "default_role_name": "research_analyst",
        "default_skill_ids": [],
        "default_tool_ids": [],
        "policy_config": {
            "max_iterations": 1,
            "allow_file_write": False,
            "run_lint": False,
            "run_build": False,
            "run_unit_tests": False,
        },
    },
]


def get_builtin_role_templates():
    return BUILTIN_ROLE_TEMPLATES
