NODE_TYPE_START = "start"
NODE_TYPE_INPUT = "input"
NODE_TYPE_AGENT = "agent"
NODE_TYPE_CONDITION = "condition"
NODE_TYPE_OUTPUT = "output"
NODE_TYPE_TOOL = "tool"

VALID_NODE_TYPES = {NODE_TYPE_START, NODE_TYPE_INPUT, NODE_TYPE_AGENT, NODE_TYPE_CONDITION, NODE_TYPE_OUTPUT, NODE_TYPE_TOOL}

RUN_STATUS_PENDING = "pending"
RUN_STATUS_RUNNING = "running"
RUN_STATUS_SUCCESS = "success"
RUN_STATUS_FAILED = "failed"
RUN_STATUS_CANCELLED = "cancelled"

VALID_RUN_STATUSES = {RUN_STATUS_PENDING, RUN_STATUS_RUNNING, RUN_STATUS_SUCCESS, RUN_STATUS_FAILED, RUN_STATUS_CANCELLED}
